<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Customer_model extends CI_Model
{

    public $table = 'mt_client';
    public $id = 'client_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('client_id', $q);
	$this->db->or_like('social_strategy', $q);
	$this->db->or_like('first_name', $q);
	$this->db->or_like('last_name', $q);
	$this->db->or_like('email_address', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('street', $q);
	$this->db->or_like('city', $q);
	$this->db->or_like('state', $q);
	$this->db->or_like('zipcode', $q);
	$this->db->or_like('country_code', $q);
	$this->db->or_like('location_name', $q);
	$this->db->or_like('contact_phone', $q);
	$this->db->or_like('lost_password_token', $q);
	$this->db->or_like('date_created', $q);
	$this->db->or_like('date_modified', $q);
	$this->db->or_like('last_login', $q);
	$this->db->or_like('ip_address', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('token', $q);
	$this->db->or_like('mobile_verification_code', $q);
	$this->db->or_like('mobile_verification_date', $q);
	$this->db->or_like('custom_field1', $q);
	$this->db->or_like('custom_field2', $q);
	$this->db->or_like('avatar', $q);
	$this->db->or_like('email_verification_code', $q);
	$this->db->or_like('is_guest', $q);
	$this->db->or_like('id_session', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('client_id', $q);
	$this->db->or_like('social_strategy', $q);
	$this->db->or_like('first_name', $q);
	$this->db->or_like('last_name', $q);
	$this->db->or_like('email_address', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('street', $q);
	$this->db->or_like('city', $q);
	$this->db->or_like('state', $q);
	$this->db->or_like('zipcode', $q);
	$this->db->or_like('country_code', $q);
	$this->db->or_like('location_name', $q);
	$this->db->or_like('contact_phone', $q);
	$this->db->or_like('lost_password_token', $q);
	$this->db->or_like('date_created', $q);
	$this->db->or_like('date_modified', $q);
	$this->db->or_like('last_login', $q);
	$this->db->or_like('ip_address', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('token', $q);
	$this->db->or_like('mobile_verification_code', $q);
	$this->db->or_like('mobile_verification_date', $q);
	$this->db->or_like('custom_field1', $q);
	$this->db->or_like('custom_field2', $q);
	$this->db->or_like('avatar', $q);
	$this->db->or_like('email_verification_code', $q);
	$this->db->or_like('is_guest', $q);
	$this->db->or_like('id_session', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Customer_model.php */
/* Location: ./application/models/Customer_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-06-02 02:10:17 */
/* http://harviacode.com */