<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Customer_model extends CI_Model
{

    public $table = 'ts_customer';
    public $id = 'customer_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('customer_id', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('surname', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('phone', $q);
	$this->db->or_like('address1', $q);
	$this->db->or_like('address2', $q);
	$this->db->or_like('city', $q);
	$this->db->or_like('country', $q);
	$this->db->or_like('zip', $q);
	$this->db->or_like('langlat', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('fb_id', $q);
	$this->db->or_like('g_id', $q);
	$this->db->or_like('g_photo', $q);
	$this->db->or_like('creation_date', $q);
	$this->db->or_like('google_plus', $q);
	$this->db->or_like('skype', $q);
	$this->db->or_like('facebook', $q);
	$this->db->or_like('wishlist', $q);
	$this->db->or_like('last_login', $q);
	$this->db->or_like('downloads', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('customer_id', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('surname', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('phone', $q);
	$this->db->or_like('address1', $q);
	$this->db->or_like('address2', $q);
	$this->db->or_like('city', $q);
	$this->db->or_like('country', $q);
	$this->db->or_like('zip', $q);
	$this->db->or_like('langlat', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('fb_id', $q);
	$this->db->or_like('g_id', $q);
	$this->db->or_like('g_photo', $q);
	$this->db->or_like('creation_date', $q);
	$this->db->or_like('google_plus', $q);
	$this->db->or_like('skype', $q);
	$this->db->or_like('facebook', $q);
	$this->db->or_like('wishlist', $q);
	$this->db->or_like('last_login', $q);
	$this->db->or_like('downloads', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Customer_model.php */
/* Location: ./application/models/Customer_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-01-26 09:40:39 */
/* http://harviacode.com */