<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Item_model extends CI_Model
{

    public $table = 'mt_item';
    public $id = 'item_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('item_id', $q);
	$this->db->or_like('merchant_id', $q);
	$this->db->or_like('item_name', $q);
	$this->db->or_like('item_description', $q);
	$this->db->or_like('item_address', $q);
	$this->db->or_like('item_latitude', $q);
	$this->db->or_like('item_longitude', $q);
	$this->db->or_like('date_start', $q);
	$this->db->or_like('time_start', $q);
	$this->db->or_like('date_finish', $q);
	$this->db->or_like('time_finish', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('category', $q);
	$this->db->or_like('price', $q);
	$this->db->or_like('qty', $q);
	$this->db->or_like('addon_item', $q);
	$this->db->or_like('cooking_ref', $q);
	$this->db->or_like('discount', $q);
	$this->db->or_like('multi_option', $q);
	$this->db->or_like('multi_option_value', $q);
	$this->db->or_like('photo', $q);
	$this->db->or_like('sequence', $q);
	$this->db->or_like('is_featured', $q);
	$this->db->or_like('date_created', $q);
	$this->db->or_like('date_modified', $q);
	$this->db->or_like('ip_address', $q);
	$this->db->or_like('ingredients', $q);
	$this->db->or_like('spicydish', $q);
	$this->db->or_like('two_flavors', $q);
	$this->db->or_like('two_flavors_position', $q);
	$this->db->or_like('require_addon', $q);
	$this->db->or_like('dish', $q);
	$this->db->or_like('item_name_trans', $q);
	$this->db->or_like('item_description_trans', $q);
	$this->db->or_like('non_taxable', $q);
	$this->db->or_like('not_available', $q);
	$this->db->or_like('gallery_photo', $q);
	$this->db->or_like('points_earned', $q);
	$this->db->or_like('points_disabled', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('item_id', $q);
	$this->db->or_like('merchant_id', $q);
	$this->db->or_like('item_name', $q);
	$this->db->or_like('item_description', $q);
	$this->db->or_like('item_address', $q);
	$this->db->or_like('item_latitude', $q);
	$this->db->or_like('item_longitude', $q);
	$this->db->or_like('date_start', $q);
	$this->db->or_like('time_start', $q);
	$this->db->or_like('date_finish', $q);
	$this->db->or_like('time_finish', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('category', $q);
	$this->db->or_like('price', $q);
	$this->db->or_like('qty', $q);
	$this->db->or_like('addon_item', $q);
	$this->db->or_like('cooking_ref', $q);
	$this->db->or_like('discount', $q);
	$this->db->or_like('multi_option', $q);
	$this->db->or_like('multi_option_value', $q);
	$this->db->or_like('photo', $q);
	$this->db->or_like('sequence', $q);
	$this->db->or_like('is_featured', $q);
	$this->db->or_like('date_created', $q);
	$this->db->or_like('date_modified', $q);
	$this->db->or_like('ip_address', $q);
	$this->db->or_like('ingredients', $q);
	$this->db->or_like('spicydish', $q);
	$this->db->or_like('two_flavors', $q);
	$this->db->or_like('two_flavors_position', $q);
	$this->db->or_like('require_addon', $q);
	$this->db->or_like('dish', $q);
	$this->db->or_like('item_name_trans', $q);
	$this->db->or_like('item_description_trans', $q);
	$this->db->or_like('non_taxable', $q);
	$this->db->or_like('not_available', $q);
	$this->db->or_like('gallery_photo', $q);
	$this->db->or_like('points_earned', $q);
	$this->db->or_like('points_disabled', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Item_model.php */
/* Location: ./application/models/Item_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-06-02 09:10:03 */
/* http://harviacode.com */